Fix for sporadic error during file overwriting [sc-68101]
dataiku/dss-plugin-onedrive pull request #5
Opened 2021-10-01 15:32 UTC by alexbourret

2021-11-10 16:09 UTC, Marsobad requested changes
- The overwriting of existing files work on my side! The retry process looks good to me. Should we set a maximum duration for the retry process if the upload of a very large file blocks everything? 
- We need to fix the code env however, as this version of urllib3 is incompatible with the requests version of DSS core package
- Don't forget to bump the version number and update the change log (or perhaps it's done in another PR? )

2021-11-10 17:38 UTC, alexbourret commented on code-env/python/spec/requirements.txt
> +urllib3==1.26.5
Done in https://github.com/dataiku/dss-plugin-onedrive/pull/8/commits/8e87ca40f77b01ff035e8e7608e2896740d48cd8 (which is in PR #8)

2021-11-10 17:39 UTC, alexbourret commented on python-lib/onedrive_client.py
>      def create_upload_session(self, path, metadata=None):
Fixed in https://github.com/dataiku/dss-plugin-onedrive/pull/5/commits/314ec82e9f6aab5281c7a8bc2394084ec4d9caef

2021-11-10 17:39 UTC, alexbourret commented on python-fs-providers/onedrive_onedrive-fs/fs-provider.py
> +        ret = self.list_recursive(path, full_path, first_non_empty)
Ooops, that's probably a debug session left over... Fixed in https://github.com/dataiku/dss-plugin-onedrive/pull/5/commits/d1f96b8046096a562823274b989ceaec7f1690fc

2021-11-15 13:54 UTC, Marsobad reviewed
LGTM! Let's wait for the PR with the unit and integration tests before merging it.

2021-11-26 15:23 UTC, merged